<?php

namespace invoiceFormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceCorrectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceCorrectiveRepository extends EntityRepository {

    public function CountAllByCurrentMonth() {
        $currentMonthYear = date('Y-m') . '%';
        $qb = $this->getEntityManager()->createQueryBuilder();
        $countedInvoices = $qb
                ->select('COUNT(i)')
                ->from('invoiceFormBundle:Invoice', 'i')
                ->where('i.issueDate LIKE :current')
                ->setParameter('current', $currentMonthYear)
                ->getQuery()
                ->getOneOrNullResult();

        return $countedInvoices;
    }
}
