<?php

namespace invoiceFormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PositionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionsRepository extends EntityRepository
{
}
